---
- name: "Create blank files"
  hosts: all
  become: yes 
  tasks:
    - name: "Create webd.txt"
      file: 
        path: /tmp/web.txt
        state: touch
        mode: 0777
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"