apiVersion: v1
kind: Service
metadata:
  name: app-register-service
spec:
  selector:
    app: app-register
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 8080
  type: LoadBalancer  # Adjust type if needed