# Task 1
#
# The playbook currently runs an echo command to print a fruit name. 
# Apply a loop directive (with_items) to the task to print all fruits defined in the fruits variable.
#
-
    name: 'Print list of fruits'
    hosts: localhost
    vars:
        fruits:
            - Apple
            - Banana
            - Grapes
            - Orange
    tasks:
        -
            command: 'echo "{{ items }}"'
            with_items: '{{ fruits }}'
#
# END -- Task 1
# 
# Task 2 -- Start
#
# To a more realistic use case. We are attempting to install multiple packages using yum module.
# The current playbook installs only a single package.
#
-
    name: 'Install required packages'
    hosts: localhost
    vars:
        packages:
            - httpd
            - binutils
            - glibc
            - ksh
            - libaio
            - libXext
            - gcc
            - make
            - sysstat
            - unixODBC
            - mongodb
            - nodejs
            - grunt
    tasks:
        -
            yum: 
                name: '{{ items }}' 
                state: present
            with_items: '{{ packages }}'
